---
- name: Configure Server
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: Install NodeJS
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


